spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/offlinepay
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#jwt
jwt.secret=5M7zPq9Lx2VnR8kJf4BwYc1DhNs6UaEeQ3tZmX9LpKv7Hi2CrFg8JnWd0SyAuMbTx
jwt.expiration=86400000
server.port=8080